# Generated by Django 4.2.11 on 2024-05-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_temporary_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporary_avatar',
            name='temp_avatar',
            field=models.ImageField(default=None, upload_to='images/users', verbose_name='ава'),
        ),
    ]
