# Generated by Django 4.2.11 on 2024-06-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_temporary_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
