# Generated by Django 4.2.11 on 2024-07-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.CharField(choices=[[1, 2], ['1', '2']], help_text='напишите отзыв здесь', max_length=250, verbose_name='отзыв'),
        ),
    ]
