# Generated by Django 4.2.11 on 2024-04-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_reviews_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='balanse',
            new_name='balance',
        ),
    ]
