# Generated by Django 4.2.11 on 2024-05-26 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_balanse_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='temporary_avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_avatar', models.ImageField(default=None, upload_to='images/temporary', verbose_name='ава')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
