# Generated by Django 4.2.11 on 2024-07-06 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0002_menu_quantity_shoppingcart_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='скидка'),
        ),
        migrations.AddField(
            model_name='menu',
            name='percent_discount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='скидка в процентах'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='int_discount',
            field=models.IntegerField(default=0, verbose_name='скидка'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='percent_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='скидка в процентах'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='покупатель'),
        ),
    ]
